# Package Overview
package_name: career_app_model

# Data Files
training_data_file: model_data.csv
test_data_file: user_training_data.csv
n_estimators: 100

# Variables
# The variable we are attempting to predict (sale price)
target: SuitabilityScore

model_name: career_app_model
model_save_file: career_app_model_output_v

features:
  - responseToQuestion1
  - responseToQuestion2
  - responseToQuestion3
  - responseToQuestion4
  - responseToQuestion5
  - responseToQuestion6
  - responseToQuestion7
  - responseToQuestion8
  - responseToQuestion9
  - responseToQuestion10
  - responseToQuestion11
  - responseToQuestion12
  - responseToQuestion13
  - responseToQuestion14
  - responseToQuestion15
  - responseToQuestion16
  - responseToQuestion17
  - responseToQuestion18
  - responseToQuestion19
  - responseToQuestion20
  - selectedIndustry1
  - selectedIndustry2
  - selectedIndustry3
  - selectedIndustry4
  - selectedIndustry5

# set train/test split
test_size: 0.2

# to set the random seed
random_state: 42

# Embeddings dimension
embedding_dimension: 437
